server:
  port: 0

spring:
  application:
    name: workforce-service

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://18.225.8.32:8761/eureka
  instance:
    preferIpAddress: true



springdoc:
  swagger-ui.path: /swagger