spring:
  application:
    name: workforce-service

server:
  port: 0


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


#datadog:
#  enabled: true
#  apiKey: 0961133ce5cce8d0d3af2f652a27e92e
#  applicationKey: e5541e192fa78b906e84c1880d52021973a83a17
#  hostTag: ${spring.application.name}